jobAPP/urls.py
from django.urls import path
from . import views


app_name = 'jobAPP'

urlpatterns = [
# post views
    path('', views.job_list, name='job_list'),
    path('<int:id>/', views.job_detail, name='job_detail'),
    path('<int:post_id>/application/', views.post_application, name='post_application'),
]

jobProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from jobAPP import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('job/', include('jobAPP.urls', namespace='jobAPP')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobAPP/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=Job_Model.Status.PUBLISHED)




class Job_Model(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    recruiter = models.ForeignKey(User, on_delete=models.CASCADE, related_name='job_posts')
    body = models.TextField()
    location = models.CharField(max_length=250)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    
    
    objects = models.Manager()       # The default manager.
    published = PublishedManager()   # Our Custom Manager.
    
    
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
        
    def __str__(self):
        return self.title
        
        
        
        
        
        # Comment = Application
        # Post = Job_Model
        # body = coverletter
        


class Application(models.Model):
    post = models.ForeignKey(Job_Model, on_delete=models.CASCADE, related_name='applications')
    name = models.CharField(max_length=180)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    coverletter = models.TextField(max_length=1500)
    cv = models.FileField(blank=True, null=True, upload_to='cvs')
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
        
        
    def __str__(self):
        return f'Application from {self.name} for the Position of {self.post}'
        
        

jobAPP/forms.py
from .models import Application
from django import forms



class ApplicationForm(forms.ModelForm):
    
    class Meta:
        model = Application
        
        fields = ['name', 'email', 'phone', 'coverletter', 'cv']

jobAPP/views.py
from django.shortcuts import render, get_object_or_404
from .models import Job_Model, Application
from django.http import Http404
from django.core.paginator import Paginator
from .forms import ApplicationForm
from django.views.decorators.http import require_POST

# Create your views here.





def job_list(request):
    job_list = Job_Model.published.all()
    paginator = Paginator(job_list, 3)
    page_number = request.GET.get('page', 1)
    posts = paginator.page(page_number)
    return render(request, 'job/post/list.html', {'posts': posts})
    
    
    
    
    
def job_detail(request, id):
    # Form for users to comment
    form = ApplicationForm()
    post = get_object_or_404(Job_Model, id=id, status=Job_Model.Status.PUBLISHED)
    return render(request, 'job/post/detail.html', {'post': post, 'form': form})
    

    
    
    
@require_POST
def post_application(request, post_id):
    post = get_object_or_404(Job_Model, id=post_id, status=Job_Model.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = ApplicationForm(request.POST, request.FILES)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
        
    return render(request, 'job/post/application.html', {'post': post, 'form': form, 'comment': comment})
        
        
        
        

jobAPP/templates/job/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="content">{% block content %} {% endblock %}</div>
    <div id="sidebar">
      <h2>Job Vacancies</h2>
      <p><a href="{% url 'jobAPP:job_list' %}">Click Here to View All Vacancies</a></p>
    </div>
  </body>
</html>

jobAPP/templates/job/post/application.html
{% extends "job/base.html" %}

{% block title %}Submit Application{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your application has been submitted.</h2>
        <p><a href="{% url 'jobAPP:job_detail' post.id %}">Back to the application</a></p>
    {% else %}
        {% include "job/post/includes/application_form.html" %}
    {% endif %}
{% endblock %}

jobAPP/templates/job/post/detail.html
{% extends "job/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.recruiter }}
  </p>
  {{ post.body|linebreaks }}
  <p class="date">
    <h4>Job Location: {{ post.location }}</h4>
  </p>
  
  {% include "job/post/include/application_form.html" %}
  
{% endblock %}

jobAPP/templates/job/post/include/application_form.html
<h2>Apply for the Job</h2>
<form action="{% url "jobAPP:post_application" post.id %}" method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Submit application"></p>
    
</form>

jobAPP/templates/job/post/list.html
{% extends "job/base.html" %}

{% block title %}Job Portal{% endblock %}

{% block content %}
  <h1>Job Vacancies</h1>
  {% for post in posts %}
    <h2>
      <a href="{% url 'jobAPP:job_detail' post.id %}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Published {{ post.publish }} by {{ post.recruiter }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
    {{ post.location }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

jobAPP/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        
    <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>